version: "3"
services:
  sobrus-react-container:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_ENV=development
      - HTTPS=true
      - PORT=443
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "workspacev2.sobus.ovh:127.0.0.1"
    #env_file:
    #./.env